In [7]:
#Numpy arrays
#creating a array
import numpy as np
a=np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [8]:
a=np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
#the difference b/w using formaly and by using numpy,it gives fast response and efficiancy
l=range(100)
%timeit[i**2 for i in l]

58.7 µs ± 789 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [10]:
a=np.arange(100)
%timeit a**2 

1.24 µs ± 9.62 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [11]:
#creating 1-D array
a=np.array([6,7,8,9,10])
#a=np.arange(10)
a

array([ 6,  7,  8,  9, 10])

In [12]:
#print dimensions
a.ndim


1

In [14]:
#shape
a.shape

(5,)

In [15]:
#creating a 2-D array
b=np.array([[1,2,3],[4,5,6]])
b

array([[1, 2, 3],
       [4, 5, 6]])

In [16]:
#to find the length
len(b)


2

In [17]:
#to find the shape
b.shape

(2, 3)

In [18]:
#dimensions
b.ndim

2

In [19]:
#3-D array
c=np.array([[[1,2,3],[4,5,6]],[[3,2,1],[6,5,4]]])
c

array([[[1, 2, 3],
        [4, 5, 6]],

       [[3, 2, 1],
        [6, 5, 4]]])

In [20]:
#to find the shape
c.shape

(2, 2, 3)

In [21]:
#dimensions
c.ndim

3

In [22]:
#functions for creating arrays
#using arrange functions
a=np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
#using a range function
import numpy as np
a=np.arange(1,10,2)
a

array([1, 3, 5, 7, 9])

In [24]:
#using linspace
a = np.linspace(0, 1, 6) #start, end, number of points
a

array([0. , 0.2, 0.4, 0.6, 0.8, 1. ])

In [25]:
#common arrays
#once matrix
a=np.ones((3,3))
a

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [26]:
#zero matrix
a=np.zeros((3,3))
a

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [27]:
#diagonal matrix
a=np.eye(3)
a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [15]:
#creating a array using random
#uniform
a=np.random.rand(4)
a

array([0.36200716, 0.02834722, 0.32563375, 0.65575113])

In [28]:
#standard
a=np.random.randn(4)
a

array([ 1.39587631, -1.14398415, -1.62202384,  0.79118306])

In [29]:
#Data types
#you will get type what do you get
a=np.arange(10)
a.dtype

dtype('int32')

In [30]:
#you will get fixed type
a=np.arange(10,dtype="float64")
a

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [31]:
a = np.zeros((3, 3))
print(a)
a.dtype

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


dtype('float64')

In [32]:
#other data types
d = np.array([1+2j, 2+4j])   #Complex datatype
print(d.dtype)

complex128


In [33]:
b = np.array([True, False, True, False])  #Boolean datatype
print(b.dtype)

bool


In [34]:
s = np.array(['Ram', 'Robert', 'Rahim'])
s.dtype

dtype('<U6')

In [35]:
#indexing
a=np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [36]:
a[5]

5

In [37]:
a=np.diag([1,2,3])
a

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [38]:
a[2,2]

3

In [39]:
a[2,1]=5
a

array([[1, 0, 0],
       [0, 2, 0],
       [0, 5, 3]])

In [40]:
#slicing
a=np.arange(10)
print(a[:2])

[0 1]


In [41]:
a[1:8:2]

array([1, 3, 5, 7])

In [42]:
a=np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [43]:
#from 1 to 5 you get order and then remaing all values are assaigned to 10 only
a = np.arange(10)
a[5:] = 10
a

array([ 0,  1,  2,  3,  4, 10, 10, 10, 10, 10])

In [44]:
#rom 1 to 5 you get order and then remaing all values are reversed
b = np.arange(5)
a[5:] = b[::-1]  #assigning
a

array([0, 1, 2, 3, 4, 4, 3, 2, 1, 0])

In [45]:
#copies and views
a=np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [46]:
b=a[::2]
b

array([0, 2, 4, 6, 8])

In [47]:
#memories are same
np.shares_memory(a,b)

True

In [54]:
#assaigning value
b[0]=10
b

array([10,  2,  4,  6,  8])

In [55]:
#eventhough we modified b,  it updated 'a' because both shares same memory
a

array([19,  0, 17, 14, 10, 18,  3, 18,  6,  1, 10, 14, 14, 10, 12])

In [56]:
a = np.arange(10)
c = a[::2].copy()     #force a copy
c

array([0, 2, 4, 6, 8])

In [57]:
#eventhough we force to copy,but the memory location is different 
np.shares_memory(a,b)

False

In [58]:
c[0]=10
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [62]:
#fancy indensing
#Using Boolean Mask
import numpy as np
a = np.random.randint(0, 20, 15)
a

array([15, 18,  6, 10,  9,  8,  5,  4, 15, 12,  3,  8, 17,  8,  7])

In [63]:
mask = (a % 2 == 0)
mask

array([False,  True,  True,  True, False,  True, False,  True, False,
        True, False,  True, False,  True, False])

In [64]:
extract_from_a = a[mask]
extract_from_a

array([18,  6, 10,  8,  4, 12,  8,  8])

In [65]:
#Indexing with a mask can be very useful to assign a new value to a sub-array:
a[mask] = -1
a

array([15, -1, -1, -1,  9, -1,  5, -1, 15, -1,  3, -1, 17, -1,  7])

In [7]:
#Indexing with an array of integers
a = np.arange(0, 100, 10)
a

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [8]:
#Indexing with an array of integers
a = np.arange(0, 100, 10)
a

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [9]:
#Indexing can be done with an array of integers, where the same index is repeated several time:
a[[2, 3, 2, 4, 2]]


array([20, 30, 20, 40, 20])

In [10]:
# New values can be assigned 
a[[9, 7]] = -200
a

array([   0,   10,   20,   30,   40,   50,   60, -200,   80, -200])