In [4]:
#element wise operatoras
import numpy as np
a=np.arange(4)
a

array([0, 1, 2, 3])

In [5]:
a+1

array([1, 2, 3, 4])

In [6]:
a**2

array([0, 1, 4, 9], dtype=int32)

In [7]:
#All arithmetic operates elementwise
b=np.ones(4)
b+1



array([2., 2., 2., 2.])

In [8]:
a-b

array([-1.,  0.,  1.,  2.])

In [9]:
a*b

array([0., 1., 2., 3.])

In [10]:
#matrix multiplication
c=np.diag([1,2,3,4])
c

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [11]:
c*c


array([[ 1,  0,  0,  0],
       [ 0,  4,  0,  0],
       [ 0,  0,  9,  0],
       [ 0,  0,  0, 16]])

In [12]:
c.dot(c)

array([[ 1,  0,  0,  0],
       [ 0,  4,  0,  0],
       [ 0,  0,  9,  0],
       [ 0,  0,  0, 16]])

In [13]:
#comparisons
a = np.array([1, 2, 3, 4])
b = np.array([5, 2, 2, 4])
a == b


array([False,  True, False,  True])

In [14]:
a < b

array([ True, False, False, False])

In [15]:
#array-wise comparisions
a = np.array([1, 2, 3, 4])
b = np.array([5, 2, 2, 4])
c = np.array([1, 2, 3, 4])

np.array_equal(a, b)

False

In [16]:
np.array_equal(a, c)

True

In [18]:
#logical operations(and,or)
a = np.array([1, 1, 0, 0], dtype=bool)
b = np.array([1, 0, 1, 0], dtype=bool)

np.logical_or(a, b)

array([ True,  True,  True, False])

In [19]:
np.logical_and(a, b)

array([ True, False, False, False])

In [20]:
#transcendental operations
a=np.arange(5)
np.sin(a)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [21]:
np.exp(a)

array([ 1.        ,  2.71828183,  7.3890561 , 20.08553692, 54.59815003])

In [22]:
np.log(a)

C:\Users\HP\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436])

In [25]:
#Basic reductions
#sum operations
a=np.array([1,2,3,4])
np.sum(a)

10

In [33]:
#sum by rows and by columns
x = np.array([[1, 1], [2, 2]])
x

array([[1, 1],
       [2, 2]])

In [35]:
x.sum(axis=0)#column first dimension

array([3, 3])

In [36]:
x.sum(axis=1)#row first dimension

array([2, 4])

In [37]:
#other reductions
x=np.array([1,2,3])
x.max()

3

In [38]:
x.min()

1

In [39]:
x.argmax()#you will get max value if index

2

In [40]:
x.argmin()#you will get min value if index

0

In [41]:
#logical operations
np.all([True, True, False])#all should be matched

False

In [42]:
np.any([True, True, False])#any one should be matched

True

In [43]:
#Note: can be used for array comparisions
a = np.zeros((50, 50))
np.any(a != 0)

False

In [44]:
np.all(a==a)

True

In [45]:
a = np.array([1, 2, 3, 2])
b = np.array([2, 2, 3, 2])
c = np.array([6, 4, 4, 5])
((a <= b) & (b <= c)).all()

True

In [46]:
x = np.array([1, 2, 3, 1])
y = np.array([[1, 2, 3], [5, 6, 1]])
x.mean()

1.75

In [47]:
np.median(x)

1.5

In [48]:
np.median(y, axis=-1) # last axis

array([2., 5.])

In [49]:
x.std()          # full population standard dev.


0.82915619758885

In [52]:
#statistics
import numpy as np
data = np.loadtxt('populations.txt')
data

array([[ 1900., 30000.,  4000., 48300.],
       [ 1901., 47200.,  6100., 48200.],
       [ 1902., 70200.,  9800., 41500.],
       [ 1903., 77400., 35200., 38200.],
       [ 1904., 36300., 59400., 40600.],
       [ 1905., 20600., 41700., 39800.],
       [ 1906., 18100., 19000., 38600.],
       [ 1907., 21400., 13000., 42300.],
       [ 1908., 22000.,  8300., 44500.],
       [ 1909., 25400.,  9100., 42100.],
       [ 1910., 27100.,  7400., 46000.],
       [ 1911., 40300.,  8000., 46800.],
       [ 1912., 57000., 12300., 43800.],
       [ 1913., 76600., 19500., 40900.],
       [ 1914., 52300., 45700., 39400.],
       [ 1915., 19500., 51100., 39000.],
       [ 1916., 11200., 29700., 36700.],
       [ 1917.,  7600., 15800., 41800.],
       [ 1918., 14600.,  9700., 43300.],
       [ 1919., 16200., 10100., 41300.],
       [ 1920., 24700.,  8600., 47300.]])

In [53]:
year, hares, lynxes, carrots = data.T #columns to variables
print(year)

[1900. 1901. 1902. 1903. 1904. 1905. 1906. 1907. 1908. 1909. 1910. 1911.
 1912. 1913. 1914. 1915. 1916. 1917. 1918. 1919. 1920.]


In [54]:
#The mean population over time
populations = data[:, 1:]
populations

array([[30000.,  4000., 48300.],
       [47200.,  6100., 48200.],
       [70200.,  9800., 41500.],
       [77400., 35200., 38200.],
       [36300., 59400., 40600.],
       [20600., 41700., 39800.],
       [18100., 19000., 38600.],
       [21400., 13000., 42300.],
       [22000.,  8300., 44500.],
       [25400.,  9100., 42100.],
       [27100.,  7400., 46000.],
       [40300.,  8000., 46800.],
       [57000., 12300., 43800.],
       [76600., 19500., 40900.],
       [52300., 45700., 39400.],
       [19500., 51100., 39000.],
       [11200., 29700., 36700.],
       [ 7600., 15800., 41800.],
       [14600.,  9700., 43300.],
       [16200., 10100., 41300.],
       [24700.,  8600., 47300.]])

In [55]:
#sample standard deviations
populations.std(axis=0)

array([20897.90645809, 16254.59153691,  3322.50622558])

In [56]:
#which species has the highest population each year?

np.argmax(populations, axis=1)

array([2, 2, 0, 0, 1, 1, 2, 2, 2, 2, 2, 2, 0, 0, 0, 1, 2, 2, 2, 2, 2],
      dtype=int64)

In [59]:
#broad casting
a = np.tile(np.arange(0, 40, 10), (4,1))
print(a)
print("*************")
a=a.T
print(a)

[[ 0 10 20 30]
 [ 0 10 20 30]
 [ 0 10 20 30]
 [ 0 10 20 30]]
*************
[[ 0  0  0  0]
 [10 10 10 10]
 [20 20 20 20]
 [30 30 30 30]]


In [60]:
b = np.array([0, 1, 2])
b

array([0, 1, 2])

In [61]:
a+b

ValueError: operands could not be broadcast together with shapes (4,4) (3,) 

In [62]:
a = np.arange(0, 40, 10)
#a.shape
a

array([ 0, 10, 20, 30])

In [63]:
a = a[:,np.newaxis]  # adds a new axis -> 2D array
a.shape#it adds the column

(4, 1)

In [64]:
a

array([[ 0],
       [10],
       [20],
       [30]])

In [65]:
a+b

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22],
       [30, 31, 32]])

In [71]:
##array shape manipulation
a = np.array([[1, 2, 3,7], [4, 5, 6,8]])
a.ravel() #Return a contiguous flattened array. A 1-D array, containing the elements of the input, is returned. A copy is made only if needed.

array([1, 2, 3, 7, 4, 5, 6, 8])

In [72]:
a.T #Transpose

array([[1, 4],
       [2, 5],
       [3, 6],
       [7, 8]])

In [73]:
a.T.ravel()#converts 2d to 1d

array([1, 4, 2, 5, 3, 6, 7, 8])

In [74]:
print(a.shape)
a

(2, 4)


array([[1, 2, 3, 7],
       [4, 5, 6, 8]])

In [75]:
b=a.ravel()
b

array([1, 2, 3, 7, 4, 5, 6, 8])

In [76]:
b.shape

(8,)

In [78]:
b=b.reshape(2,4)
b

array([[1, 2, 3, 7],
       [4, 5, 6, 8]])

In [79]:
b[0,0]=100#b value updates,similarly a value also updates
b

array([[100,   2,   3,   7],
       [  4,   5,   6,   8]])

In [80]:
a

array([[100,   2,   3,   7],
       [  4,   5,   6,   8]])

In [81]:
#reshape also returns a copy
a=np.zeros([3,2])
b=a.T.reshape([3,2])
b[0,0]==50
a

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [82]:
#adding dimension
p=np.array([1,2,3])
p

array([1, 2, 3])

In [83]:
p[:, np.newaxis]


array([[1],
       [2],
       [3]])

In [86]:
#dimensuion shifting
a=np.arange(4*3*2).reshape(4,3,2)#no of matrices,rows,columns
a.shape

(4, 3, 2)

In [87]:
a

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15],
        [16, 17]],

       [[18, 19],
        [20, 21],
        [22, 23]]])

In [88]:
a[0,1,1]

3

In [89]:
#resizing
a = np.arange(4)
a.resize((8,))
a

array([0, 1, 2, 3, 0, 0, 0, 0])

In [92]:
b = a#we cant rsize by giving reference
a.resize((4,)) 

ValueError: cannot resize an array that references or is referenced
by another array in this way.  Use the resize function

In [93]:
#sorting data
#Sorting along an axis:
a = np.array([[5, 4, 6], [2, 3, 2]])
b = np.sort(a, axis=1)
b

array([[4, 5, 6],
       [2, 2, 3]])

In [94]:
#in-place sort
a.sort(axis=1)
a

array([[4, 5, 6],
       [2, 2, 3]])

In [95]:
#sorting with fancy indexing
a = np.array([4, 3, 1, 2])
j = np.argsort(a)
j

array([2, 3, 1, 0], dtype=int64)

In [128]:
a[j]

array([1, 2, 3, 4])